/// Flutter icons InspectIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InspectIcon
///      fonts:
///       - asset: fonts/InspectIcon.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class InspectIcon {
  InspectIcon._();

  static const _kFontFam = 'InspectIcon';
  static const String? _kFontPkg = null;

  static const IconData cog_alt =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paint_roller =
      IconData(0xf5aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fan =
      IconData(0xf863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_video =
      IconData(0xf87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
