// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/settings/infrastructure/dtos/settings_info_object.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(2, 3001466626796540502),
      name: 'SettingsInfoObject',
      lastPropertyId: const IdUid(2, 8634447605141739819),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4100404361310067183),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8634447605141739819),
            name: 'themeMode',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 3001466626796540502),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [3418513866095141367],
      retiredIndexUids: const [],
      retiredPropertyUids: const [4399980086611291794, 4537754755790352345],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    SettingsInfoObject: EntityDefinition<SettingsInfoObject>(
        model: _entities[0],
        toOneRelations: (SettingsInfoObject object) => [],
        toManyRelations: (SettingsInfoObject object) => {},
        getId: (SettingsInfoObject object) => object.id,
        setId: (SettingsInfoObject object, int id) {
          object.id = id;
        },
        objectToFB: (SettingsInfoObject object, fb.Builder fbb) {
          final themeModeOffset = object.themeMode == null
              ? null
              : fbb.writeString(object.themeMode!);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, themeModeOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = SettingsInfoObject(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              themeMode: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [SettingsInfoObject] entity fields to define ObjectBox queries.
class SettingsInfoObject_ {
  /// see [SettingsInfoObject.id]
  static final id =
      QueryIntegerProperty<SettingsInfoObject>(_entities[0].properties[0]);

  /// see [SettingsInfoObject.themeMode]
  static final themeMode =
      QueryStringProperty<SettingsInfoObject>(_entities[0].properties[1]);
}
