###
GET http://192.168.0.117:9090/cut HTTP/1.1 
Content-Type: application/json

###
GET http://192.168.0.117:9090/cut/req?date=2022-04-05&seq=1 HTTP/1.1 
Content-Type: application/json

###
GET http://192.168.0.117:9090/cut/check?date=2022-04-05&seq=1 HTTP/1.1 
Content-Type: application/json

###
POST http://192.168.0.117:9090/sign-in HTTP/1.1 
Content-Type: application/json

{
    "id":"SYSTEM"
}

###
GET http://192.168.0.117:9090/qm?wb-cd=FWP&page=1 HTTP/1.1 
Content-Type: application/json

###
GET http://192.168.0.117:9090/fct HTTP/1.1 
Content-Type: application/json

###
GET http://192.168.0.117:9090/fct/2022-04-20 HTTP/1.1 
Content-Type: application/json