###
GET http://192.168.0.117:9090/cut HTTP/1.1 
Content-Type: application/json

###
GET http://192.168.0.117:9090/cut/req?date=2022-04-19&seq=1 HTTP/1.1
Content-Type: application/json

###
GET http://192.168.0.117:9090/cut/check?date=2022-04-19&seq=1 HTTP/1.1

Content-Type: application/json

###
POST http://192.168.0.117:9090/sign-in HTTP/1.1
Content-Type: application/json

{
    "id":"SYSTEM"
}

###
GET http://192.168.35.242:9090/order?page=1&code=FP2 HTTP/1.1
###
POST http://192.168.35.242:9090/sign-in HTTP/1.1
Content-Type: application/json

{
    "id":"SYSTEM"
}

###
GET http://192.168.35.242:9090/wb HTTP/1.1
Content-Type: application/json


GET http://192.168.0.117:9090/qm?wb-cd=FWP&page=1 HTTP/1.1
Content-Type: application/json

###
GET http://172.16.30.105:9090/fct HTTP/1.1
Content-Type: application/json

###
GET http://192.168.0.117:9090/fct/2022-04-20 HTTP/1.1
Content-Type: application/json

###
POST http://192.168.0.117:9090/cut/check HTTP/1.1
Content-Type: application/json

{
    "date": "2022-04-19",
    "seq": "1",
    "wo-nb": "P21-025944",
    "width": "0.0",
    "height": "0.0",
    "thickness": "0.0",
    "angle": "0.0",
    "lot": "test",
    "work-id": "test",
    "equip-cd": "test",
    "remark": "test",
    "user-id": "test"
}

###
GET http://192.168.0.117:9090/checklist?prod-seq=581646&wo-nb=P21-024730&wb-cd=FNP&wc-cd=79&page-cd=QM2 HTTP/1.1
Content-Type: application/json

###
GET http://192.168.0.117:9090/checklist?prod-seq=545754&wo-nb=P20-032662&wb-cd=FFL&wc-cd=36&page-cd= HTTP/1.1
Content-Type: application/json

###
GET http://192.168.0.117:9090/checklist?prod-seq=579442&wo-nb=P21-024609&wb-cd=FNP&wc-cd=27&page-cd=QM1 HTTP/1.1
Content-Type: application/json

###
GET http://192.168.0.117:9090/checklist?prod-seq=592415&wo-nb=P21-056129&wb-cd=FCT&wc-cd=35&page-cd= HTTP/1.1
Content-Type: application/json

###
GET http://192.168.35.242:9090/unit?code=TBL_TYPE HTTP/1.1
Content-Type: application/json

###
GET http://192.168.0.117:9090/menu?code=Q HTTP/1.1
Content-Type: application/json

###
GET http://192.168.0.117:9090/wb HTTP/1.1
Content-Type: application/json

###
GET http://192.168.0.117:9090/order?page=1&wb-cd=FP2&wc-cd=33 HTTP/1.1
Content-Type: application/json
